### ISSUE TITLE
Project-specific conventions (guidelines)

### ISSUE THREAD

**Issue by LePython** [noah1510/redhand#49]
The conventions have to be specified somewhere for a project of this size. This will also help the new developers to maintain the code similarity between the different project modules. This issue isn't a high priority, however it has to be done in the near future.

**Comment by noah1510** [comment]
the is a .clang-format file which allows for automatic code formatting, other than that the guidlines are mostly common sense:

* do not use raw pointers unless it is the only way you can do it
* apply the styling rules from the .clang-format
* for public and protected variables use names that have a meaning (not foor, bar, etc.)
* the same for class names and namespaces
* all redhand code should be in the redhand namespace
* all redhand headers should be in the all.hpp header

**Comment by LePython** [comment]
Alright, didn't know about automatic code formatting. Im closing the issue, although there are some things that I'd suggest to add in the c headers: the description (overview) of each class in docstring style + additional information like a link to the github page.

**Comment by noah1510** [comment]
> the description (overview) of each class in docstring style + additional information like a link to the github page.

All classes should have doxygen documentation which automatically generates the github pages and the man pages.
If redhand is installed using the debian package you can type `man redhand` to get some documentation.
If you build the documentation yourself it is located in the doc folder.
You can either open the html documentation by opening `doc/html/index.html` in a browser or the generated man pages using e.g. `man ./doc/man/libredhand/redhand_Actor.3`.

**Comment by LePython** [comment]
Thanks for the explanation. I am using Windows 10 at the moment and having hard time running the engine altogether. I'll try documenting my problems while trying to fix them, since the installation doc isn't sufficient to run the engine.

**Comment by noah1510** [comment]
Well it is not for windows at the moment, just install msys2 and run the scripts
